name: Gerar Tetris GIF

on:
  # Roda automaticamente uma vez por dia
  schedule:
    - cron: '0 0 * * *'
  # Permite rodar manualmente pela aba "Actions"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # importante para evitar conflitos de histórico

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pillow

      - name: Gerar Tetris GIF
        run: |
          python scripts/generate_tetris.py --out tetris.gif --frames 200

      - name: Commit e push do GIF gerado
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tetris.gif || true

          if ! git diff --cached --quiet; then
            git commit -m "Atualiza tetris.gif (automatizado)"
            # Evita erros de non-fast-forward
            git pull --rebase origin ${{ github.ref_name }}
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "Nenhuma alteração para comitar."
          fi
