name: Gerar Tetris GIF

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install pillow

      - name: Gerar Tetris GIF
        run: python scripts/generate_tetris.py

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commitar e enviar GIF
        run: |
          git add tetris.gif
          git commit -m "Atualiza Tetris GIF (automatizado)" || echo "Nada para commitar"
          git pull --rebase
          git push
